# docker-compose up
app:
  image: ibmcom/swift-ubuntu:4.0.2
  volumes:
    - .:/Kitura-Net
  command: bash -c "cd /Kitura-Net && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test --build-path .build-ubuntu"
